### ISSUE TITLE
Seeking Team Consensus

### ISSUE THREAD

**Issue by Alkass** [Lamassau/pitrol-generic-template#1]
Do we have an agreement on the template layout portrayed in this repository?

**Comment by AlKass** [comment]
@fadeenk , @AlhasanIQ , @Ahmed-90 
I'm still awaiting your response

**Comment by fadeenk** [comment]
I am extremely busy right now cant really take a look till the weekend probably

**Comment by Ahmed-90** [comment]
same as @fadeenk way too busy 😭 
had a quick look... its fine for now

**Comment by AlhasanIQ** [comment]
perfect for me
